project_id = "hdjgkjceownmmnrqqtuz"

[functions.invoice-checkout-issue]
verify_jwt = true

[functions.auth-email-hook]
verify_jwt = false

[functions.request-inline-otp]
verify_jwt = false

[functions.verify-inline-otp]

[functions.process-email-queue]
verify_jwt = true


