import { PGlite } from '@electric-sql/pglite';
import { readFile } from 'node:fs/promises';
import assert from 'node:assert/strict';
const db = new PGlite();
const root='4365e913-36f1-432e-ab16-748c3ca6826a', product='2b7bf6d4-ad8d-46ad-9399-7f96c307c596', flow='b10e15c5-51c3-5df5-ba83-a42416da5902';
const id=n=>`00000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
const [buyer,oldBuyer,expired,admin,tariff,otherTariff,child,disabled,otherModule,lesson1,lesson2,lesson3,oldLesson,legacyProduct]=[1,2,3,4,5,6,7,8,9,10,11,12,13,14].map(id);
await db.exec(`
 CREATE ROLE anon; CREATE ROLE authenticated; CREATE ROLE service_role BYPASSRLS;
 CREATE SCHEMA auth;
 CREATE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql STABLE AS $$ SELECT nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;
 CREATE FUNCTION auth.jwt() RETURNS jsonb LANGUAGE sql STABLE AS $$ SELECT jsonb_build_object('role',current_setting('request.jwt.claim.role',true)) $$;
 CREATE FUNCTION public.has_role_v2(u uuid,r text) RETURNS boolean LANGUAGE sql STABLE AS $$ SELECT u='${admin}'::uuid AND r='admin' $$;
 CREATE FUNCTION public.has_permission(u uuid,p text) RETURNS boolean LANGUAGE sql STABLE AS $$ SELECT false $$;
 CREATE TABLE public.training_modules(id uuid PRIMARY KEY,parent_module_id uuid,product_id uuid,is_active boolean,published_at timestamptz);
 CREATE TABLE public.training_lessons(id uuid PRIMARY KEY,module_id uuid,is_active boolean,published_at timestamptz,require_previous boolean,sort_order int,title text,slug text,content_type text,content text,video_url text);
 CREATE TABLE public.flows(id uuid PRIMARY KEY,product_id uuid,start_date date,end_date date,is_active boolean,meta jsonb,updated_at timestamptz);
 CREATE TABLE public.entitlement_sources(user_id uuid,product_id uuid,tariff_id uuid,status text,starts_at timestamptz,expires_at timestamptz);
 CREATE TABLE public.subscriptions_v2(user_id uuid,product_id uuid,tariff_id uuid,status text,access_start_at timestamptz,access_end_at timestamptz);
 CREATE TABLE public.entitlements(user_id uuid,product_id uuid,status text,expires_at timestamptz,meta jsonb);
 CREATE TABLE public.access_rules(id uuid,product_id uuid,tariff_id uuid,is_active boolean,grant_target_type text,target_ref text,conditions jsonb);
 CREATE TABLE public.module_access(module_id uuid,tariff_id uuid);
 CREATE TABLE public.lesson_blocks(id uuid,lesson_id uuid,content jsonb);
 CREATE TABLE public.lesson_attachments(id uuid,lesson_id uuid);
 CREATE TABLE public.lesson_progress(user_id uuid,lesson_id uuid);
 CREATE TABLE public.lesson_progress_state(user_id uuid,lesson_id uuid);
 CREATE TABLE public.user_lesson_progress(user_id uuid,lesson_id uuid);
 CREATE TABLE public.orders_v2(id uuid,status text);
 CREATE TABLE public.order_group_items(id uuid,order_id uuid,order_group_id uuid,role text,product_id uuid,item_snapshot jsonb);
 CREATE TABLE public.scheduled_product_access(order_group_id uuid,status text,access_delivery_mode text,opens_at timestamptz,updated_at timestamptz);
 CREATE TABLE public.audit_logs(action text,actor_type text CONSTRAINT audit_logs_actor_type_check CHECK (actor_type IN ('user','system','service')),actor_user_id uuid,entity_type text,entity_id text,meta jsonb);
 CREATE TABLE public.tariffs(id uuid PRIMARY KEY,product_id uuid);
 CREATE TABLE public.tariff_offers(id uuid PRIMARY KEY,tariff_id uuid,is_active boolean,meta jsonb);
 CREATE TABLE public.offer_addons(parent_offer_id uuid,is_active boolean,access_delivery_mode text,access_opens_at timestamptz);
 CREATE FUNCTION public.user_has_training_lesson_access(_user_id uuid,_lesson_id uuid) RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER AS $$SELECT true$$;
 INSERT INTO public.flows VALUES('${flow}','${product}','2026-10-23','2026-12-10',true,'{}',now());
 INSERT INTO public.training_modules VALUES ('${root}',null,'${product}',true,null),('${child}','${root}','${product}',true,null),('${disabled}','${root}','${product}',false,null),('${otherModule}',null,'${legacyProduct}',true,null);
 INSERT INTO public.training_lessons VALUES
 ('${lesson1}','${child}',true,null,false,1,'First','first','article','PRIVATE CONTENT','PRIVATE URL'),
 ('${lesson2}','${child}',true,null,true,2,'Second','second','article','PRIVATE CONTENT','PRIVATE URL'),
 ('${lesson3}','${disabled}',true,null,false,1,'Disabled','disabled','article','PRIVATE CONTENT','PRIVATE URL'),
 ('${oldLesson}','${otherModule}',true,null,false,1,'Historical','historical','article','OLD CONTENT','OLD URL');
 INSERT INTO public.entitlement_sources VALUES ('${buyer}','${product}','${tariff}','active','2026-09-01','2027-06-30'),('${oldBuyer}','${legacyProduct}','${tariff}','active','2026-09-01','2027-06-30'),('${expired}','${product}','${tariff}','active','2026-09-01','2026-09-20');
 INSERT INTO public.entitlements VALUES('${expired}','${product}','active','2027-06-30','{}');
 INSERT INTO public.access_rules VALUES('${id(20)}','${product}','${tariff}',true,'training_content','${root}','{"access_mode":"full"}');
 INSERT INTO public.lesson_blocks SELECT id,id,'{"url":"SECRET"}' FROM public.training_lessons;
 INSERT INTO public.tariffs VALUES('${tariff}','${product}');
 INSERT INTO public.tariff_offers VALUES('${id(21)}','${tariff}',true,'{}'),('${id(22)}','${tariff}',true,'{"sales_legacy_only":true}');
 INSERT INTO public.offer_addons SELECT '${id(21)}',true,'fixed_date','2026-12-09T21:00Z'::timestamptz FROM generate_series(1,128);
 INSERT INTO public.offer_addons VALUES('${id(22)}',true,'manual',null);
 INSERT INTO public.orders_v2 VALUES('${id(30)}','pending'),('${id(34)}','draft');
 INSERT INTO public.order_group_items VALUES('${id(31)}',null,'${id(32)}','primary','${product}','{}'),('${id(33)}','${id(30)}','${id(32)}','addon','${legacyProduct}','{"access_delivery_mode":"manual","price":100}'),('${id(35)}','${id(34)}','${id(32)}','addon','${legacyProduct}','{"access_delivery_mode":"manual","price":200}');
 GRANT USAGE ON SCHEMA auth,public TO authenticated,anon;
 GRANT SELECT,INSERT,UPDATE ON ALL TABLES IN SCHEMA public TO authenticated,anon;
`);
for (const table of ['training_modules','training_lessons','lesson_blocks','lesson_attachments','lesson_progress','lesson_progress_state','user_lesson_progress']) {
 await db.exec(`ALTER TABLE public.${table} ENABLE ROW LEVEL SECURITY; CREATE POLICY old_permissive ON public.${table} FOR ALL TO authenticated,anon USING(true) WITH CHECK(true);`);
}
await db.exec(await readFile(new URL('../../supabase/migrations/20260929061010_cb21_learning_release_gate.sql',import.meta.url),'utf8'));
// Match the real production CHECK: the original admin-save failure must roll back.
await db.exec(`SELECT set_config('request.jwt.claim.sub','${admin}',false);`);
await assert.rejects(db.query(`SELECT public.set_training_release_schedule('${flow}','2026-10-01',46,'manual')`),/audit_logs_actor_type_check/);
assert.equal((await db.query(`SELECT start_date::text value FROM public.flows WHERE id='${flow}'`)).rows[0].value,'2026-09-30');
const triggerBefore=(await db.query(`SELECT pg_get_functiondef('private.sync_cb21_learning_release()'::regprocedure) body`)).rows[0].body;
await db.exec(await readFile(new URL('../../supabase/migrations/20260929070426_cb21_release_audit_actor.sql',import.meta.url),'utf8'));
const triggerAfter=(await db.query(`SELECT pg_get_functiondef('private.sync_cb21_learning_release()'::regprocedure) body`)).rows[0].body;
assert.equal(triggerAfter,triggerBefore.replace("ELSE 'admin' END","ELSE 'user' END"));
assert.equal((await db.query(`SELECT count(*)::int n FROM public.audit_logs WHERE actor_type='system' AND actor_user_id IS NULL`)).rows[0].n,1);
await assert.rejects(db.query(`INSERT INTO public.audit_logs(actor_type) VALUES('admin')`),/audit_logs_actor_type_check/);
await db.exec(`SELECT set_config('request.jwt.claim.sub','',false);`);

const scalar=async(sql,args=[]) => (await db.query(sql,args)).rows[0].value;
const reason=(u,l,date)=>scalar('SELECT private.cb21_lesson_lock_reason($1,$2,$3) value',[u,l,date]);
assert.equal(await reason(buyer,lesson1,'2026-09-29T20:59:59Z'),'before_start');
assert.equal(await reason(buyer,lesson1,'2026-09-29T21:00:00Z'),null);
assert.equal(await reason(buyer,lesson3,'2026-09-30T12:00:00Z'),'unpublished');
assert.equal(await reason(buyer,lesson2,'2026-09-30T12:00:00Z'),'previous_lesson');
await db.exec(`INSERT INTO public.lesson_progress VALUES('${buyer}','${lesson1}');`);
assert.equal(await reason(buyer,lesson2,'2026-09-30T12:00:00Z'),null);
assert.equal(await reason(oldBuyer,lesson1,'2026-09-30T12:00:00Z'),'no_access');
assert.equal(await reason(expired,lesson1,'2026-09-30T12:00:00Z'),'no_access');
assert.equal(await reason(buyer,oldLesson,'2026-09-29T00:00:00Z'),null);
assert.equal(await reason(admin,lesson3,'2026-09-29T00:00:00Z'),null);
await db.exec(`UPDATE public.access_rules SET tariff_id='${otherTariff}';`);
assert.equal(await reason(buyer,lesson1,'2026-09-30T12:00:00Z'),'no_access');
await db.exec(`UPDATE public.access_rules SET tariff_id='${tariff}';`);
assert.equal(await scalar(`SELECT access_opens_at='2026-11-13T21:00:00Z'::timestamptz value FROM public.offer_addons WHERE parent_offer_id='${id(21)}'`),true);
assert.equal(await scalar(`SELECT access_delivery_mode value FROM public.offer_addons WHERE parent_offer_id='${id(22)}'`),'manual');
// Production RLS path with a real non-admin database role, not service bypass.
await db.exec(`SET ROLE authenticated; SELECT set_config('request.jwt.claim.sub','${oldBuyer}',false);`);
assert.equal(await scalar(`SELECT count(*)::int value FROM public.training_modules WHERE id='${root}'`),0);
assert.equal(await scalar(`SELECT count(*)::int value FROM public.lesson_blocks WHERE lesson_id='${lesson1}'`),0);
assert.equal(await scalar(`SELECT count(*)::int value FROM public.training_lessons WHERE id='${oldLesson}'`),1);
assert.deepEqual(await scalar(`SELECT public.get_training_release_lessons('${child}') value`),[]);
await assert.rejects(db.query(`SELECT private.cb21_lesson_lock_reason('${buyer}','${lesson1}','2030-01-01')`),/permission denied/);
await assert.rejects(db.query(`SELECT public.set_training_release_schedule('${flow}','2026-09-30',45,'manual')`),/forbidden/);
await db.exec(`RESET ROLE; UPDATE public.flows SET start_date=(current_date+2); SET ROLE authenticated; SELECT set_config('request.jwt.claim.sub','${buyer}',false);`);
assert.equal(await scalar(`SELECT count(*)::int value FROM public.lesson_blocks WHERE lesson_id='${lesson1}'`),0);
const catalogue=await scalar(`SELECT public.get_training_release_lessons('${child}') value`);
assert.equal(catalogue.length,2);
assert.equal(catalogue[0].release_lock_reason,'before_start');
assert.equal(JSON.stringify(catalogue).includes('PRIVATE'),false);
await assert.rejects(db.query(`INSERT INTO public.lesson_progress VALUES('${buyer}','${lesson2}')`),/row-level security/);
await db.exec(`RESET ROLE; UPDATE public.flows SET start_date='2026-09-30';`);
assert.equal(await scalar(`SELECT item_snapshot->>'access_delivery_mode' value FROM public.order_group_items WHERE id='${id(33)}'`),'fixed_date');
assert.equal(await scalar(`SELECT (item_snapshot->>'price')::int value FROM public.order_group_items WHERE id='${id(33)}'`),100);
assert.equal(await scalar(`SELECT item_snapshot->>'access_delivery_mode' value FROM public.order_group_items WHERE id='${id(35)}'`),'fixed_date');
assert.equal(await scalar(`SELECT (item_snapshot->>'price')::int value FROM public.order_group_items WHERE id='${id(35)}'`),200);
await db.exec(`INSERT INTO public.scheduled_product_access(order_group_id,status,access_delivery_mode,opens_at) VALUES('${id(32)}','scheduled','manual',null);`);
assert.equal(await scalar(`SELECT opens_at='2026-11-13T21:00Z'::timestamptz value FROM public.scheduled_product_access WHERE order_group_id='${id(32)}'`),true);
await db.exec(`SET ROLE authenticated; SELECT set_config('request.jwt.claim.sub','${admin}',false); SELECT public.set_training_release_schedule('${flow}','2026-09-30',45,'manual'); RESET ROLE;`);
assert.equal(await scalar(`SELECT access_delivery_mode value FROM public.scheduled_product_access WHERE order_group_id='${id(32)}'`),'manual');
assert.equal(await scalar(`SELECT opens_at value FROM public.scheduled_product_access WHERE order_group_id='${id(32)}'`),null);
assert.equal(await scalar(`SELECT count(*)::int value FROM public.audit_logs WHERE actor_type='user' AND actor_user_id='${admin}'`),1);
// A subscription-only purchaser uses the same CB21 gate without manufacturing an entitlement.
await db.exec(`INSERT INTO public.subscriptions_v2 VALUES('${id(50)}','${product}','${tariff}','active','2026-09-01','2027-06-30'); UPDATE public.flows SET start_date=current_date-1; SET ROLE authenticated; SELECT set_config('request.jwt.claim.sub','${id(50)}',false);`);
assert.equal(await scalar(`SELECT public.user_has_training_lesson_access('${id(50)}','${lesson1}') value`),true);
assert.equal(await scalar(`SELECT count(*)::int value FROM public.training_modules WHERE id='${root}'`),1);
assert.equal(await scalar(`SELECT count(*)::int value FROM public.training_lessons WHERE id='${lesson1}'`),1);
assert.equal(await scalar(`SELECT count(*)::int value FROM public.training_lessons WHERE id='${lesson3}'`),0);
await db.close();
console.log('CB21 release gate: date boundaries, isolation, tariff, expiry, inactive ancestry, sequence, redaction, RLS, manual settings authorization PASS');
