import { createClient } from "https://esm.sh/@supabase/supabase-js@2.49.4";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type",
};

function json(data: unknown, status = 200) {
  return new Response(JSON.stringify(data), {
    status,
    headers: { ...corsHeaders, "Content-Type": "application/json" },
  });
}

// ─── Normalization helpers ───

function normalizeEmail(v: string): string | null {
  if (!v) return null;
  const cleaned = v.trim().toLowerCase();
  return cleaned.includes("@") ? cleaned : null;
}

function normalizePhone(v: string): string | null {
  if (!v) return null;
  const cleaned = v.replace(/[^\d+]/g, "");
  if (cleaned.replace(/\D/g, "").length < 9) return null;
  return cleaned;
}

function normalizeTelegram(v: string): string | null {
  if (!v) return null;
  let cleaned = v.trim().toLowerCase();
  cleaned = cleaned.replace(/^https?:\/\/(t\.me|telegram\.me)\//, "");
  cleaned = cleaned.replace(/^@/, "");
  return cleaned || null;
}

function phoneLast9(phone: string): string {
  return phone.replace(/\D/g, "").slice(-9);
}

// ─── Types ───

interface FormField {
  label: string;
  type: string;
  value: string;
  mapping?: string;
}

interface RequestBody {
  page_id: string;
  fields: FormField[];
}

// ─── Main ───

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response("ok", { headers: corsHeaders });
  }

  try {
    // 1. Parse & validate
    const body: RequestBody = await req.json();
    const { page_id, fields } = body;

    if (!page_id || typeof page_id !== "string") {
      return json({ error: "page_id is required" }, 400);
    }
    if (!Array.isArray(fields) || fields.length === 0) {
      return json({ error: "fields must be a non-empty array" }, 400);
    }

    // Check at least one field has a value
    const hasValue = fields.some((f) => f.value && f.value.trim());
    if (!hasValue) {
      return json({ error: "At least one field must have a value" }, 400);
    }

    // 2. Service client
    const supabaseUrl = Deno.env.get("SUPABASE_URL")!;
    const serviceKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
    const admin = createClient(supabaseUrl, serviceKey);

    // 3. Get workspace_id from site_pages
    const { data: page, error: pageError } = await admin
      .from("site_pages")
      .select("id, workspace_id")
      .eq("id", page_id)
      .single();

    if (pageError || !page) {
      return json({ error: "Page not found" }, 400);
    }

    const workspaceId = page.workspace_id;

    // 4. Build form_data and field_mapping
    const formData: Record<string, string> = {};
    const fieldMapping: Record<string, string> = {};
    const mappedValues: Record<string, string> = {};

    for (const field of fields) {
      const key = field.label || `field_${fields.indexOf(field)}`;
      formData[key] = field.value || "";
      if (field.mapping && field.mapping !== "none" && field.value) {
        fieldMapping[key] = field.mapping;
        mappedValues[field.mapping] = field.value;
      }
    }

    // 5. INSERT submission (public_id auto-generated by trigger)
    const { data: submission, error: subError } = await admin
      .from("site_form_submissions")
      .insert({
        public_id: "",
        workspace_id: workspaceId,
        page_id,
        form_data: formData,
        field_mapping: fieldMapping,
        status: "new",
        source: "site_form",
        metadata: {},
      })
      .select("id, public_id")
      .single();

    if (subError || !submission) {
      console.error("Insert submission error:", subError);
      return json({ error: "Failed to create submission" }, 500);
    }

    // 6. Domain event
    await admin.from("domain_events").insert({
      event_type: "site_form_submitted",
      entity_type: "site_form_submission",
      entity_id: submission.id,
      payload: {
        page_id,
        workspace_id: workspaceId,
        submission_id: submission.id,
        public_id: submission.public_id,
        mapped_fields: Object.keys(mappedValues),
      },
      status: "pending",
    });

    // 7. CRM resolve step
    let profileId: string | null = null;
    let resolveStatus = "skipped";
    let resolveDetails: Record<string, unknown> = { reason: "no_identifiers" };

    const email = mappedValues.email
      ? normalizeEmail(mappedValues.email)
      : null;
    const phone = mappedValues.phone
      ? normalizePhone(mappedValues.phone)
      : null;
    const telegram = mappedValues.telegram_username
      ? normalizeTelegram(mappedValues.telegram_username)
      : null;

    const hasIdentifier = email || phone || telegram;

    if (hasIdentifier) {
      // Sequential dedup: email → phone → telegram
      let matchedProfiles: Array<{ id: string }> = [];
      let matchType = "";

      if (email) {
        const { data } = await admin
          .from("profiles")
          .select("id")
          .ilike("email", email)
          .neq("status", "archived")
          .limit(5);
        if (data && data.length > 0) {
          matchedProfiles = data;
          matchType = "email";
        }
      }

      if (matchedProfiles.length === 0 && phone) {
        const last9 = phoneLast9(phone);
        if (last9.length === 9) {
          const { data } = await admin
            .from("profiles")
            .select("id, phone")
            .neq("status", "archived")
            .not("phone", "is", null);

          if (data) {
            const matched = data.filter((p) => {
              const pLast9 = p.phone
                ? p.phone.replace(/\D/g, "").slice(-9)
                : "";
              return pLast9 === last9;
            });
            if (matched.length > 0) {
              matchedProfiles = matched.map((m) => ({ id: m.id }));
              matchType = "phone";
            }
          }
        }
      }

      if (matchedProfiles.length === 0 && telegram) {
        const { data } = await admin
          .from("profiles")
          .select("id")
          .ilike("telegram_username", telegram)
          .neq("status", "archived")
          .limit(5);
        if (data && data.length > 0) {
          matchedProfiles = data;
          matchType = "telegram";
        }
      }

      if (matchedProfiles.length === 1) {
        // Exact match
        profileId = matchedProfiles[0].id;
        resolveStatus = "matched";
        resolveDetails = {
          match_type: matchType,
          profile_id: profileId,
        };
      } else if (matchedProfiles.length > 1) {
        // Ambiguous — do NOT link, log as data quality issue
        resolveStatus = "failed";
        resolveDetails = {
          error: "ambiguous_profile_match",
          match_type: matchType,
          matched_count: matchedProfiles.length,
          matched_ids: matchedProfiles.map((p) => p.id),
          email,
          phone,
          telegram,
        };

        // Audit log for ambiguous match
        await admin.from("audit_logs").insert({
          action: "site_form_ambiguous_match",
          actor_type: "system",
          actor_label: "site-form-submit",
          meta: {
            submission_id: submission.id,
            ...resolveDetails,
          },
        });
      } else {
        // No match — create ghost profile
        const newProfile: Record<string, unknown> = {
          source: "site_form",
          status: "active",
        };

        if (email) newProfile.email = email;
        if (phone) newProfile.phone = phone;
        if (telegram) newProfile.telegram_username = telegram;
        if (mappedValues.full_name) newProfile.full_name = mappedValues.full_name;
        if (mappedValues.first_name) newProfile.first_name = mappedValues.first_name;
        if (mappedValues.last_name) newProfile.last_name = mappedValues.last_name;

        const { data: newP, error: createErr } = await admin
          .from("profiles")
          .insert(newProfile)
          .select("id")
          .single();

        if (createErr) {
          console.error("Create profile error:", createErr);
          resolveStatus = "failed";
          resolveDetails = {
            error: "profile_creation_failed",
            message: createErr.message,
          };
        } else {
          profileId = newP!.id;
          resolveStatus = "created";
          resolveDetails = {
            profile_id: profileId,
            fields_set: Object.keys(newProfile),
          };
        }
      }

      // Update submission with profile_id if resolved
      if (profileId) {
        await admin
          .from("site_form_submissions")
          .update({ profile_id: profileId, status: "processed" })
          .eq("id", submission.id);
      }
    }

    // 8. Domain execution
    await admin.from("domain_executions").insert({
      event_type: "site_form_submitted",
      entity_type: "site_form_submission",
      entity_id: submission.id,
      step: "crm_resolve_profile",
      status: resolveStatus === "failed" ? "failed" : "completed",
      result: resolveDetails,
    });

    // 9. Audit log
    await admin.from("audit_logs").insert({
      action: "site_form_submission_created",
      actor_type: "system",
      actor_label: "site-form-submit",
      meta: {
        submission_id: submission.id,
        public_id: submission.public_id,
        page_id,
        workspace_id: workspaceId,
        profile_id: profileId,
        resolve_status: resolveStatus,
      },
    });

    return json({
      success: true,
      submission_id: submission.id,
    });
  } catch (err) {
    console.error("site-form-submit error:", err);
    return json({ error: "Internal server error" }, 500);
  }
});
