-- Private visitor journal: the bearer key is generated by the Edge Function.
-- No direct browser inserts, no raw IP addresses and no personal data in stats.
CREATE TABLE public.site_questionnaire_journeys (
  id uuid PRIMARY KEY,
  page_id uuid NOT NULL REFERENCES public.site_pages(id),
  key_hash text NOT NULL CHECK(key_hash ~ '^[a-f0-9]{64}$'),
  attribution jsonb NOT NULL DEFAULT '{}',
  first_seen_at timestamptz NOT NULL DEFAULT now(),
  last_seen_at timestamptz NOT NULL DEFAULT now(),
  profile_id uuid REFERENCES public.profiles(id),
  account_outcome text CHECK(account_outcome IN ('new_account','existing_account')),
  outcome_at timestamptz
);
CREATE TABLE public.site_questionnaire_visits (
  id uuid PRIMARY KEY,
  journey_id uuid NOT NULL REFERENCES public.site_questionnaire_journeys(id),
  seen_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX site_questionnaire_visits_journey ON public.site_questionnaire_visits(journey_id,seen_at);
CREATE INDEX site_questionnaire_journeys_page ON public.site_questionnaire_journeys(page_id,first_seen_at);
CREATE TABLE public.site_questionnaire_visit_limits (
  ip_hash text PRIMARY KEY CHECK(ip_hash ~ '^[a-f0-9]{64}$'),
  window_start timestamptz NOT NULL,
  attempts integer NOT NULL CHECK(attempts>0)
);
ALTER TABLE public.site_questionnaire_journeys ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.site_questionnaire_visits ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.site_questionnaire_visit_limits ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.site_questionnaire_journeys,public.site_questionnaire_visits,public.site_questionnaire_visit_limits FROM PUBLIC,anon,authenticated;
GRANT ALL ON public.site_questionnaire_journeys,public.site_questionnaire_visits,public.site_questionnaire_visit_limits TO service_role;

CREATE OR REPLACE FUNCTION public.track_site_questionnaire_visit(
  p_journey_id uuid,p_key_hash text,p_visit_id uuid,p_page_id uuid,p_attribution jsonb,p_ip_hash text)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=public,pg_temp AS $$
DECLARE v_page jsonb; v_j public.site_questionnaire_journeys%ROWTYPE; v_attempts integer; v_key text; v_value jsonb; v_count integer;
BEGIN
  IF p_journey_id IS NULL OR p_visit_id IS NULL OR p_page_id IS NULL
    OR p_key_hash IS NULL OR p_key_hash !~ '^[a-f0-9]{64}$'
    OR p_ip_hash IS NULL OR p_ip_hash !~ '^[a-f0-9]{64}$'
    OR jsonb_typeof(p_attribution) IS DISTINCT FROM 'object' THEN RAISE EXCEPTION 'journey_invalid' USING ERRCODE='22023'; END IF;
  FOR v_key,v_value IN SELECT * FROM jsonb_each(p_attribution) LOOP
    IF v_key NOT IN ('src','utm_source','utm_medium','utm_campaign','utm_content','utm_term')
      OR jsonb_typeof(v_value)<>'string' OR length(v_value#>>'{}')>200
      OR (v_value#>>'{}')~'[[:cntrl:]]' THEN RAISE EXCEPTION 'journey_attribution_invalid' USING ERRCODE='22023'; END IF;
  END LOOP;
  SELECT blocks INTO v_page FROM site_pages WHERE id=p_page_id AND status='published' FOR SHARE;
  IF NOT FOUND OR NOT EXISTS(SELECT 1 FROM jsonb_array_elements(v_page) b WHERE b->>'type'='form'
    AND b->'content'->'questionnaire_first'='true'::jsonb AND b->'content'->'auth_mode'='true'::jsonb)
    THEN RAISE EXCEPTION 'journey_page_unavailable' USING ERRCODE='22023'; END IF;
  INSERT INTO site_questionnaire_visit_limits(ip_hash,window_start,attempts) VALUES(p_ip_hash,date_trunc('minute',now()),1)
    ON CONFLICT(ip_hash) DO UPDATE SET
      attempts=CASE WHEN site_questionnaire_visit_limits.window_start=date_trunc('minute',now()) THEN site_questionnaire_visit_limits.attempts+1 ELSE 1 END,
      window_start=date_trunc('minute',now()) RETURNING attempts INTO v_attempts;
  IF v_attempts>30 THEN RETURN jsonb_build_object('status','rate_limited'); END IF;
  PERFORM pg_advisory_xact_lock(hashtextextended('questionnaire_journey:'||p_journey_id::text,0));
  SELECT * INTO v_j FROM site_questionnaire_journeys WHERE id=p_journey_id FOR UPDATE;
  IF FOUND THEN
    IF v_j.key_hash<>p_key_hash OR v_j.page_id<>p_page_id THEN RAISE EXCEPTION 'journey_owner_invalid' USING ERRCODE='42501'; END IF;
  ELSE
    INSERT INTO site_questionnaire_journeys(id,page_id,key_hash,attribution) VALUES(p_journey_id,p_page_id,p_key_hash,p_attribution);
  END IF;
  INSERT INTO site_questionnaire_visits(id,journey_id) VALUES(p_visit_id,p_journey_id) ON CONFLICT(id) DO NOTHING;
  GET DIAGNOSTICS v_count=ROW_COUNT;
  IF NOT EXISTS(SELECT 1 FROM site_questionnaire_visits WHERE id=p_visit_id AND journey_id=p_journey_id)
    THEN RAISE EXCEPTION 'journey_visit_conflict' USING ERRCODE='42501'; END IF;
  IF v_count=1 THEN UPDATE site_questionnaire_journeys SET last_seen_at=now() WHERE id=p_journey_id; END IF;
  RETURN jsonb_build_object('status','tracked','replayed',v_count=0);
END;
$$;
REVOKE ALL ON FUNCTION public.track_site_questionnaire_visit(uuid,text,uuid,uuid,jsonb,text) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.track_site_questionnaire_visit(uuid,text,uuid,uuid,jsonb,text) TO service_role;

-- Called inside the atomic submission, after ownership was proved by email/JWT.
CREATE OR REPLACE FUNCTION public.bind_site_questionnaire_journey(p_journey_id uuid,p_key_hash text,p_submission_id uuid)
RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path=public,pg_temp AS $$
DECLARE v_j public.site_questionnaire_journeys%ROWTYPE; v_s public.site_form_submissions%ROWTYPE;
BEGIN
  SELECT * INTO v_j FROM site_questionnaire_journeys WHERE id=p_journey_id FOR UPDATE;
  SELECT * INTO v_s FROM site_form_submissions WHERE id=p_submission_id;
  IF v_j.id IS NULL OR v_s.id IS NULL OR p_key_hash IS NULL OR v_j.key_hash<>p_key_hash
    OR v_j.page_id<>v_s.page_id OR v_s.profile_id IS NULL OR v_s.status<>'processed'
    OR (v_j.profile_id IS NOT NULL AND v_j.profile_id<>v_s.profile_id)
    THEN RAISE EXCEPTION 'journey_binding_invalid' USING ERRCODE='42501'; END IF;
  PERFORM public.record_site_questionnaire_account_outcome(v_j.id,p_key_hash,
    (SELECT user_id FROM public.profiles WHERE id=v_s.profile_id));
  UPDATE site_form_submissions SET metadata=metadata||jsonb_build_object('journey_id',v_j.id,'attribution',v_j.attribution)
    WHERE id=v_s.id;
END;
$$;
REVOKE ALL ON FUNCTION public.bind_site_questionnaire_journey(uuid,text,uuid) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.bind_site_questionnaire_journey(uuid,text,uuid) TO service_role;

CREATE OR REPLACE FUNCTION public.site_questionnaire_funnel_stats(p_page_id uuid,p_from timestamptz,p_to timestamptz)
RETURNS TABLE(attribution jsonb,visits bigint,visitors bigint,questionnaires bigint,contacts bigint,new_accounts bigint,existing_accounts bigint,unclassified_accounts bigint)
LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path=public,pg_temp AS $$
BEGIN
  IF auth.uid() IS NULL OR NOT public.has_admin_resource_access(auth.uid(),'forms-hub','site','view') THEN
    RAISE EXCEPTION 'questionnaire_stats_forbidden' USING ERRCODE='42501'; END IF;
  IF p_from IS NULL OR p_to IS NULL OR p_to<=p_from OR p_to-p_from>interval '366 days' THEN
    RAISE EXCEPTION 'questionnaire_stats_range_invalid' USING ERRCODE='22023'; END IF;
  RETURN QUERY WITH selected AS (
    SELECT j.* FROM site_questionnaire_journeys j WHERE j.page_id=p_page_id
  ), per_journey AS (
    SELECT j.id,j.attribution,j.profile_id,j.account_outcome,j.outcome_at,
      (SELECT count(*) FROM site_questionnaire_visits v WHERE v.journey_id=j.id AND v.seen_at>=p_from AND v.seen_at<p_to) visit_count,
      (SELECT count(*) FROM site_form_submissions s WHERE s.page_id=p_page_id AND s.status='processed'
        AND s.metadata->>'journey_id'=j.id::text AND s.created_at>=p_from AND s.created_at<p_to) form_count
    FROM selected j
  ) SELECT j.attribution,sum(j.visit_count)::bigint,count(*) FILTER(WHERE j.visit_count>0)::bigint,sum(j.form_count)::bigint,
    count(DISTINCT j.profile_id) FILTER(WHERE j.form_count>0)::bigint,
    count(DISTINCT j.profile_id) FILTER(WHERE j.account_outcome='new_account' AND j.outcome_at>=p_from AND j.outcome_at<p_to)::bigint,
    count(DISTINCT j.profile_id) FILTER(WHERE j.account_outcome='existing_account' AND j.outcome_at>=p_from AND j.outcome_at<p_to)::bigint,
    count(DISTINCT j.profile_id) FILTER(WHERE j.account_outcome IS NULL AND j.form_count>0)::bigint
    FROM per_journey j GROUP BY j.attribution HAVING sum(j.visit_count)+sum(j.form_count)+count(*) FILTER(WHERE j.outcome_at>=p_from AND j.outcome_at<p_to)>0 ORDER BY sum(j.visit_count) DESC;
END;
$$;
REVOKE ALL ON FUNCTION public.site_questionnaire_funnel_stats(uuid,timestamptz,timestamptz) FROM PUBLIC,anon;
GRANT EXECUTE ON FUNCTION public.site_questionnaire_funnel_stats(uuid,timestamptz,timestamptz) TO authenticated;

CREATE OR REPLACE FUNCTION public.read_site_questionnaire_journey_attribution(p_journey_id uuid,p_key_hash text,p_page_id uuid,p_profile_id uuid)
RETURNS jsonb LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path=public,pg_temp AS $$
DECLARE v_j public.site_questionnaire_journeys%ROWTYPE;
BEGIN
  SELECT * INTO v_j FROM site_questionnaire_journeys WHERE id=p_journey_id;
  IF v_j.id IS NULL OR p_key_hash IS NULL OR v_j.key_hash<>p_key_hash OR v_j.page_id<>p_page_id
    OR (v_j.profile_id IS NOT NULL AND v_j.profile_id IS DISTINCT FROM p_profile_id)
    THEN RAISE EXCEPTION 'journey_binding_invalid' USING ERRCODE='42501'; END IF;
  RETURN v_j.attribution||jsonb_build_object('journey_id',v_j.id);
END;
$$;
REVOKE ALL ON FUNCTION public.read_site_questionnaire_journey_attribution(uuid,text,uuid,uuid) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.read_site_questionnaire_journey_attribution(uuid,text,uuid,uuid) TO service_role;

-- Only the service endpoint may validate and persist an OTP journey context.
CREATE OR REPLACE FUNCTION public.validate_site_questionnaire_otp_journey(
 p_journey_id uuid,p_key_hash text,p_page_id uuid,p_block_id uuid,p_email text)
RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path=public,pg_temp AS $$
DECLARE v_j public.site_questionnaire_journeys%ROWTYPE;
BEGIN
 SELECT * INTO v_j FROM site_questionnaire_journeys WHERE id=p_journey_id;
 IF v_j.id IS NULL OR p_key_hash IS NULL OR v_j.key_hash<>p_key_hash OR v_j.page_id IS DISTINCT FROM p_page_id
   OR p_email IS NULL OR NOT EXISTS(SELECT 1 FROM site_pages p CROSS JOIN LATERAL jsonb_array_elements(p.blocks) b
     WHERE p.id=p_page_id AND p.status='published' AND b->>'id'=p_block_id::text AND b->>'type'='form'
       AND b->'content'->'auth_mode'='true'::jsonb AND b->'content'->'questionnaire_first'='true'::jsonb)
   OR (v_j.profile_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM profiles p JOIN auth.users u ON u.id=p.user_id
     WHERE p.id=v_j.profile_id AND lower(u.email)=lower(p_email)))
 THEN RAISE EXCEPTION 'questionnaire_context_invalid' USING ERRCODE='42501'; END IF;
END;
$$;
REVOKE ALL ON FUNCTION public.validate_site_questionnaire_otp_journey(uuid,text,uuid,uuid,text) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.validate_site_questionnaire_otp_journey(uuid,text,uuid,uuid,text) TO service_role;

-- Auth provisioning and public-schema writes are separate operations. The
-- server-only signup marker survives a fresh OTP after profile/session failures.
-- Never infer a new account from profile.created_at or user-editable metadata.
CREATE OR REPLACE FUNCTION public.record_site_questionnaire_account_outcome(
 p_journey_id uuid,p_key_hash text,p_user_id uuid)
RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path=public,pg_temp AS $$
DECLARE v_j public.site_questionnaire_journeys%ROWTYPE; v_profile uuid; v_signup text;
BEGIN
 SELECT * INTO v_j FROM site_questionnaire_journeys WHERE id=p_journey_id FOR UPDATE;
 SELECT p.id,u.raw_app_meta_data->>'questionnaire_signup_journey_id' INTO v_profile,v_signup
   FROM profiles p JOIN auth.users u ON u.id=p.user_id WHERE p.user_id=p_user_id
   AND p.status='active' AND NOT coalesce(p.is_archived,false) AND p.merged_to_profile_id IS NULL
   AND u.email_confirmed_at IS NOT NULL AND u.deleted_at IS NULL AND (u.banned_until IS NULL OR u.banned_until<=now());
 IF v_j.id IS NULL OR p_key_hash IS NULL OR v_j.key_hash<>p_key_hash OR v_profile IS NULL
   OR (v_j.profile_id IS NOT NULL AND v_j.profile_id<>v_profile)
 THEN RAISE EXCEPTION 'journey_binding_invalid' USING ERRCODE='42501'; END IF;
 UPDATE site_questionnaire_journeys SET profile_id=v_profile,
   account_outcome=coalesce(account_outcome,CASE WHEN v_signup=v_j.id::text THEN 'new_account' ELSE 'existing_account' END),
   outcome_at=coalesce(outcome_at,now()) WHERE id=v_j.id;
END;
$$;
REVOKE ALL ON FUNCTION public.record_site_questionnaire_account_outcome(uuid,text,uuid) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.record_site_questionnaire_account_outcome(uuid,text,uuid) TO service_role;
