// One-shot probe: verifies which verifyOtp `type` accepts email OTP tokens
// generated by Supabase Admin for signup vs magiclink flows.
// Safe to delete after PATCH-INLINE-AUTH-EMAIL-OTP-FLOW Phase 2 is proven.
import { createClient } from 'npm:@supabase/supabase-js@2'

const cors = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, content-type, apikey',
}

const SUPABASE_URL = Deno.env.get('SUPABASE_URL')!
const SERVICE_KEY = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!
const ANON_KEY = Deno.env.get('SUPABASE_ANON_KEY')!
const TEST_EMAIL = 'otp-probe+staging@gorbova.by'

Deno.serve(async (req) => {
  if (req.method === 'OPTIONS') return new Response(null, { headers: cors })
  const results: any = { email: TEST_EMAIL, steps: [] }
  const admin = createClient(SUPABASE_URL, SERVICE_KEY, { auth: { persistSession: false } })

  try {
    // Cleanup: delete existing test user if present
    const { data: list } = await admin.auth.admin.listUsers({ page: 1, perPage: 200 })
    const existing = list?.users?.find((u) => u.email === TEST_EMAIL)
    if (existing) {
      await admin.auth.admin.deleteUser(existing.id)
      results.steps.push({ step: 'cleanup', deleted: existing.id })
    }

    // --- Case A: signup flow ---
    const signupLink = await admin.auth.admin.generateLink({
      type: 'signup',
      email: TEST_EMAIL,
      password: crypto.randomUUID() + 'Aa1!',
    })
    const signupOtp = signupLink.data?.properties?.email_otp
    results.steps.push({ step: 'generateLink:signup', got_otp: !!signupOtp, error: signupLink.error?.message })

    if (signupOtp) {
      // Try type='email'
      const anonA = createClient(SUPABASE_URL, ANON_KEY, { auth: { persistSession: false } })
      const vE = await anonA.auth.verifyOtp({ email: TEST_EMAIL, token: signupOtp, type: 'email' })
      results.steps.push({ step: 'verifyOtp signup token, type=email', ok: !vE.error, error: vE.error?.message, session: !!vE.data?.session })
      if (vE.error) {
        // Try type='signup'
        const anonB = createClient(SUPABASE_URL, ANON_KEY, { auth: { persistSession: false } })
        const vS = await anonB.auth.verifyOtp({ email: TEST_EMAIL, token: signupOtp, type: 'signup' })
        results.steps.push({ step: 'verifyOtp signup token, type=signup', ok: !vS.error, error: vS.error?.message, session: !!vS.data?.session })
      }
    }

    // Cleanup between cases
    const { data: list2 } = await admin.auth.admin.listUsers({ page: 1, perPage: 200 })
    const existing2 = list2?.users?.find((u) => u.email === TEST_EMAIL)
    if (existing2) await admin.auth.admin.deleteUser(existing2.id)

    // --- Case B: magiclink flow (existing user) ---
    // First create user (confirmed) so magiclink can be issued
    const created = await admin.auth.admin.createUser({
      email: TEST_EMAIL,
      email_confirm: true,
      password: crypto.randomUUID() + 'Aa1!',
    })
    results.steps.push({ step: 'createUser for magiclink', ok: !created.error, error: created.error?.message })

    const magicLink = await admin.auth.admin.generateLink({ type: 'magiclink', email: TEST_EMAIL })
    const magicOtp = magicLink.data?.properties?.email_otp
    results.steps.push({ step: 'generateLink:magiclink', got_otp: !!magicOtp, error: magicLink.error?.message })

    if (magicOtp) {
      const anonC = createClient(SUPABASE_URL, ANON_KEY, { auth: { persistSession: false } })
      const vE2 = await anonC.auth.verifyOtp({ email: TEST_EMAIL, token: magicOtp, type: 'email' })
      results.steps.push({ step: 'verifyOtp magic token, type=email', ok: !vE2.error, error: vE2.error?.message, session: !!vE2.data?.session })
      if (vE2.error) {
        const anonD = createClient(SUPABASE_URL, ANON_KEY, { auth: { persistSession: false } })
        const vM = await anonD.auth.verifyOtp({ email: TEST_EMAIL, token: magicOtp, type: 'magiclink' })
        results.steps.push({ step: 'verifyOtp magic token, type=magiclink', ok: !vM.error, error: vM.error?.message, session: !!vM.data?.session })
      }
    }

    // Final cleanup
    const { data: list3 } = await admin.auth.admin.listUsers({ page: 1, perPage: 200 })
    const existing3 = list3?.users?.find((u) => u.email === TEST_EMAIL)
    if (existing3) await admin.auth.admin.deleteUser(existing3.id)

    // Decide recommended type
    const signupEmailOk = results.steps.find((s: any) => s.step === 'verifyOtp signup token, type=email')?.ok
    const magicEmailOk = results.steps.find((s: any) => s.step === 'verifyOtp magic token, type=email')?.ok
    results.recommendation = signupEmailOk && magicEmailOk
      ? "type: 'email' works for BOTH flows — use unified"
      : "type: 'email' unreliable — fall back to per-flow ('signup' vs 'magiclink')"
  } catch (e) {
    results.fatal = (e as Error).message
  }

  return new Response(JSON.stringify(results, null, 2), {
    headers: { ...cors, 'content-type': 'application/json' },
  })
})
